site_name: FIP wiki
nav:
    - Home: Index.md 
    - FIP Wizard 3.0 User Guide:
      - Background: Background.md
      - Overview: Overview.md
      - Getting started: GettingStarted.md
      - Minting nanopublications: MintingNanopublications.md
      - Publishing: Publishing.md
      - Revising: Revising.md
      - Authors: Authors.md
    - License: License.md
    - Maintainers: Maintainers.md

theme: readthedocs

markdown_extensions:
    - footnotes
